### ISSUE TITLE
Reboot command gives Invalid path error

### ISSUE THREAD

**Issue by daelvn** [Piorjade/cLinux#12]

**Comment by GReaperEx** [comment]
Yeah, every nonexistent command gives an "Invalid path" error... It says so in the readme, it doesn't use any of the /rom/programs.

**Comment by daelvn** [comment]
However, I think the error is not appropiate/clear. Something like "Command not found" maybe

**Comment by Overflwn** [comment]
I will change that later :)

**Comment by Overflwn** [comment]
@GReaperEx 
Is right, it doesn't use any programs of the whole /rom/ folder and doesn't allow you to do that.
I might upload a reboot command (which is very simple, just make a "reboot" file in /bin/ and write os.reboot()... this should do the thing)

**Comment by Overflwn** [comment]
Well nvm it was actually a bug cuz I changed something in the shell API... fixed :)
