### ISSUE TITLE
Shell doesn't parse cmd-line arguments correctly

### ISSUE THREAD

**Issue by GReaperEx** [Piorjade/cLinux#18]
It merges some of them, and in some cases loops forever( never returning to the prompt ).

It doesn't matter what command I use, or even if it exists! If I give it more than two space-separated arguments, it hangs... But not if said arguments have "-" if front of them, for some reason...

I can't even begin to understand cmdbak, so... help?

**Comment by Overflwn** [comment]
That's really strange...

I'll look into that... AND I will try to make the cmdbak code understandable afterwards.

Anyway, thank you as always for posting issues!

**Comment by Overflwn** [comment]
@GReaperEx
Could you give me an example for arguments that work and arguments that don't work?

**Comment by daelvn** [comment]
> If I give it more than two space-separated arguments, it hangs... But not if said arguments have "-" if front of them, for some reason...

Not really strange I'd say, it's the parser issue. I will try to find the relevant code in the shell and If I do it's ready to assign the issue

**Comment by GReaperEx** [comment]
@Piorjade 
Yes, of course. Here are some examples that work:
`blah`
`blah a`
`blah abc`
`blah -a -b -c`
The last one treats "-a -b" as a single argument.

Here are some that hang everything:
`blah a b`
`blah a b c`
`etcetera`

Those are some of the commands I tried.

**Comment by Overflwn** [comment]
> > Yes, of course. Here are some examples that work:
> blah
> blah a
> blah abc
> blah -a -b -c
> The last one treats "-a -b" as a single argument.
> 
> Here are some that hang everything:
> blah a b
> blah a b c
> etcetera

Uuuum I tried those commands in stock cLinux (normal commandline / cmdbak) and everything worked as expected. Tried it with blah being non-existend and blah being existend and printing the arguments out, which treats "-a -b" as seperate arguments.

Well MAYBE I got it all wrong and you are not talking about the commandline / cmdbak, cuz I really don't get it O.o

@GReaperEx Could you tell me exactly where you are / what you are doing ? How I understood this issue: You are in the stock commandline / cmdbak and enter these commands (blah does not exist) and when entering with specific arguments ("a b" or "a b c") it hangs the commandline / cmdbak AND entering "etcetera" hangs the commandline / cmdbak too. Is that right? If yes, it doesn't happen for me... hmm

**Comment by GReaperEx** [comment]
Are you sure?! This is rather strange. What computercraft version are you using? I'm on 1.79

**Comment by GReaperEx** [comment]
@Piorjade No, "etcetera" is a placeholder for "and so on", I meant that if you kept using more arguments like that, it'd keep hanging.

Other than that, you've got it right.

EDIT: Could the cmdbak script be invoking undefined behavior while parsing the arguments? It's very strange...

**Comment by Overflwn** [comment]
@GReaperEx 
Yeah I use 1.79 and I already tried spamming arguments, no hanging.
That is indeed very strange O.o

**Comment by GReaperEx** [comment]
I don't know why it wouldn't error on your end, but I managed to fix it by changing line 606 of cmdback:
from:
`local i, j = string.find(arg, " ")`
to:
`local i, j = string.find(arg, "%s")`

Please test this change and fix it if it doesn't introduce any other problems

**Comment by Overflwn** [comment]
Wait wait wait I'm saying that it does NOT error on my end xD

**Comment by Overflwn** [comment]
Although %s is probably a better solution than " ", I will push that (as the Lua Wiki defines %s as "all space characters", so it shouldn't make any problems).
Thank you for your contribution :)

**Comment by GReaperEx** [comment]
Great, thanks. I'm implementing getopt( yes, THE getopt of linux ) and command-line parsing is, like, essential! :-)
